[package]
name = "pihole_scanner"
version = "0.1.0"
authors = ["Thejus Paul <thejuspaul@pm.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
